[package]
name = "nullnet-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
pingora-core = { version = "0.8.1", features = ["openssl"] }
pingora-proxy = "0.8.1"
pingora-http = "0.8.1"
http = "1.4"
pingora-openssl = "0.8.1"
openssl.workspace = true
arc-swap = "1"
nullnet-grpc-lib.workspace = true
nullnet-liberror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "net", "io-util", "macros", "sync", "time"] }
ctrlc = { workspace = true, features = ["termination"] }
