[package]
name = "nullnet-client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tun-rs = { version = "2.8.8", features = ["async_tokio"] }
etherparse = "0.21.0"
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["net", "sync", "rt-multi-thread", "macros", "io-util", "time", "fs", "process"] }
serde = { version = "1.0.229", default-features = false, features = ["derive", "alloc"] }
nullnet-liberror.workspace = true
nullnet-grpc-lib.workspace = true
ipnetwork = { workspace = true, features = ["serde"] }
listeners = "0.6.1"
rtnetlink = "0.23.0"
netlink-sys = { version = "0.9.0", features = ["tokio_socket"] }
futures.workspace = true
network-interface = "2.0.5"
nfq = "0.2"
aes-gcm.workspace = true
aya = "0.14"
libc = "0.2"
